package Extra_Opdrachten.ninetynine_bottles;

public class NinetyNineBottles {

	public static void main(String[] args) {
		System.out.println("99 bottles of beer on the wall, 99 bottles of beer.");
		System.out.println("Take one down and pass it around, 98 bottles of beer on the wall.");
		System.out.println("98 bottles of beer on the wall, 98 bottles of beer.");
		System.out.println("Take one down and pass it around, 97 bottles of beer on the wall.");
		System.out.println("97 bottles of beer on the wall, 97 bottles of beer.");
		System.out.println("Take one down and pass it around, 96 bottles of beer on the wall.");
		System.out.println("96 bottles of beer on the wall, 96 bottles of beer.");
		System.out.println("Take one down and pass it around, 95 bottles of beer on the wall.");
		System.out.println("95 bottles of beer on the wall, 95 bottles of beer.");
		System.out.println("Take one down and pass it around, 94 bottles of beer on the wall.");
		System.out.println("94 bottles of beer on the wall, 94 bottles of beer.");
		System.out.println("Take one down and pass it around, 93 bottles of beer on the wall.");
		System.out.println("93 bottles of beer on the wall, 93 bottles of beer.");
		System.out.println("Take one down and pass it around, 92 bottles of beer on the wall.");
		System.out.println("92 bottles of beer on the wall, 92 bottles of beer.");
		System.out.println("Take one down and pass it around, 91 bottles of beer on the wall.");
		System.out.println("91 bottles of beer on the wall, 91 bottles of beer.");
		System.out.println("Take one down and pass it around, 90 bottles of beer on the wall.");
		System.out.println("90 bottles of beer on the wall, 90 bottles of beer.");
		System.out.println("Take one down and pass it around, 89 bottles of beer on the wall.");
		System.out.println("89 bottles of beer on the wall, 89 bottles of beer.");
		System.out.println("Take one down and pass it around, 88 bottles of beer on the wall.");
		System.out.println("88 bottles of beer on the wall, 88 bottles of beer.");
		System.out.println("Take one down and pass it around, 87 bottles of beer on the wall.");
		System.out.println("87 bottles of beer on the wall, 87 bottles of beer.");
		System.out.println("Take one down and pass it around, 86 bottles of beer on the wall.");
		System.out.println("86 bottles of beer on the wall, 86 bottles of beer.");
		System.out.println("Take one down and pass it around, 85 bottles of beer on the wall.");
		System.out.println("85 bottles of beer on the wall, 85 bottles of beer.");
		System.out.println("Take one down and pass it around, 84 bottles of beer on the wall.");
		System.out.println("84 bottles of beer on the wall, 84 bottles of beer.");
		System.out.println("Take one down and pass it around, 83 bottles of beer on the wall.");
		System.out.println("83 bottles of beer on the wall, 83 bottles of beer.");
		System.out.println("Take one down and pass it around, 82 bottles of beer on the wall.");
		System.out.println("82 bottles of beer on the wall, 82 bottles of beer.");
		System.out.println("Take one down and pass it around, 81 bottles of beer on the wall.");
		System.out.println("81 bottles of beer on the wall, 81 bottles of beer.");
		System.out.println("Take one down and pass it around, 80 bottles of beer on the wall.");
		System.out.println("80 bottles of beer on the wall, 80 bottles of beer.");
		System.out.println("Take one down and pass it around, 79 bottles of beer on the wall.");
		System.out.println("79 bottles of beer on the wall, 79 bottles of beer.");
		System.out.println("Take one down and pass it around, 78 bottles of beer on the wall.");
		System.out.println("78 bottles of beer on the wall, 78 bottles of beer.");
		System.out.println("Take one down and pass it around, 77 bottles of beer on the wall.");
		System.out.println("77 bottles of beer on the wall, 77 bottles of beer.");
		System.out.println("Take one down and pass it around, 76 bottles of beer on the wall.");
		System.out.println("76 bottles of beer on the wall, 76 bottles of beer.");
		System.out.println("Take one down and pass it around, 75 bottles of beer on the wall.");
		System.out.println("75 bottles of beer on the wall, 75 bottles of beer.");
		System.out.println("Take one down and pass it around, 74 bottles of beer on the wall.");
		System.out.println("74 bottles of beer on the wall, 74 bottles of beer.");
		System.out.println("Take one down and pass it around, 73 bottles of beer on the wall.");
		System.out.println("73 bottles of beer on the wall, 73 bottles of beer.");
		System.out.println("Take one down and pass it around, 72 bottles of beer on the wall.");
		System.out.println("72 bottles of beer on the wall, 72 bottles of beer.");
		System.out.println("Take one down and pass it around, 71 bottles of beer on the wall.");
		System.out.println("71 bottles of beer on the wall, 71 bottles of beer.");
		System.out.println("Take one down and pass it around, 70 bottles of beer on the wall.");
		System.out.println("70 bottles of beer on the wall, 70 bottles of beer.");
		System.out.println("Take one down and pass it around, 69 bottles of beer on the wall.");
		System.out.println("69 bottles of beer on the wall, 69 bottles of beer.");
		System.out.println("Take one down and pass it around, 68 bottles of beer on the wall.");
		System.out.println("68 bottles of beer on the wall, 68 bottles of beer.");
		System.out.println("Take one down and pass it around, 67 bottles of beer on the wall.");
		System.out.println("67 bottles of beer on the wall, 67 bottles of beer.");
		System.out.println("Take one down and pass it around, 66 bottles of beer on the wall.");
		System.out.println("66 bottles of beer on the wall, 66 bottles of beer.");
		System.out.println("Take one down and pass it around, 65 bottles of beer on the wall.");
		System.out.println("65 bottles of beer on the wall, 65 bottles of beer.");
		System.out.println("Take one down and pass it around, 64 bottles of beer on the wall.");
		System.out.println("64 bottles of beer on the wall, 64 bottles of beer.");
		System.out.println("Take one down and pass it around, 63 bottles of beer on the wall.");
		System.out.println("63 bottles of beer on the wall, 63 bottles of beer.");
		System.out.println("Take one down and pass it around, 62 bottles of beer on the wall.");
		System.out.println("62 bottles of beer on the wall, 62 bottles of beer.");
		System.out.println("Take one down and pass it around, 61 bottles of beer on the wall.");
		System.out.println("61 bottles of beer on the wall, 61 bottles of beer.");
		System.out.println("Take one down and pass it around, 60 bottles of beer on the wall.");
		System.out.println("60 bottles of beer on the wall, 60 bottles of beer.");
		System.out.println("Take one down and pass it around, 59 bottles of beer on the wall.");
		System.out.println("59 bottles of beer on the wall, 59 bottles of beer.");
		System.out.println("Take one down and pass it around, 58 bottles of beer on the wall.");
		System.out.println("58 bottles of beer on the wall, 58 bottles of beer.");
		System.out.println("Take one down and pass it around, 57 bottles of beer on the wall.");
		System.out.println("57 bottles of beer on the wall, 57 bottles of beer.");
		System.out.println("Take one down and pass it around, 56 bottles of beer on the wall.");
		System.out.println("56 bottles of beer on the wall, 56 bottles of beer.");
		System.out.println("Take one down and pass it around, 55 bottles of beer on the wall.");
		System.out.println("55 bottles of beer on the wall, 55 bottles of beer.");
		System.out.println("Take one down and pass it around, 54 bottles of beer on the wall.");
		System.out.println("54 bottles of beer on the wall, 54 bottles of beer.");
		System.out.println("Take one down and pass it around, 53 bottles of beer on the wall.");
		System.out.println("53 bottles of beer on the wall, 53 bottles of beer.");
		System.out.println("Take one down and pass it around, 52 bottles of beer on the wall.");
		System.out.println("52 bottles of beer on the wall, 52 bottles of beer.");
		System.out.println("Take one down and pass it around, 51 bottles of beer on the wall.");
		System.out.println("51 bottles of beer on the wall, 51 bottles of beer.");
		System.out.println("Take one down and pass it around, 50 bottles of beer on the wall.");
		System.out.println("50 bottles of beer on the wall, 50 bottles of beer.");
		System.out.println("Take one down and pass it around, 49 bottles of beer on the wall.");
		System.out.println("49 bottles of beer on the wall, 49 bottles of beer.");
		System.out.println("Take one down and pass it around, 48 bottles of beer on the wall.");
		System.out.println("48 bottles of beer on the wall, 48 bottles of beer.");
		System.out.println("Take one down and pass it around, 47 bottles of beer on the wall.");
		System.out.println("47 bottles of beer on the wall, 47 bottles of beer.");
		System.out.println("Take one down and pass it around, 46 bottles of beer on the wall.");
		System.out.println("46 bottles of beer on the wall, 46 bottles of beer.");
		System.out.println("Take one down and pass it around, 45 bottles of beer on the wall.");
		System.out.println("45 bottles of beer on the wall, 45 bottles of beer.");
		System.out.println("Take one down and pass it around, 44 bottles of beer on the wall.");
		System.out.println("44 bottles of beer on the wall, 44 bottles of beer.");
		System.out.println("Take one down and pass it around, 43 bottles of beer on the wall.");
		System.out.println("43 bottles of beer on the wall, 43 bottles of beer.");
		System.out.println("Take one down and pass it around, 42 bottles of beer on the wall.");
		System.out.println("42 bottles of beer on the wall, 42 bottles of beer.");
		System.out.println("Take one down and pass it around, 41 bottles of beer on the wall.");
		System.out.println("41 bottles of beer on the wall, 41 bottles of beer.");
		System.out.println("Take one down and pass it around, 40 bottles of beer on the wall.");
		System.out.println("40 bottles of beer on the wall, 40 bottles of beer.");
		System.out.println("Take one down and pass it around, 39 bottles of beer on the wall.");
		System.out.println("39 bottles of beer on the wall, 39 bottles of beer.");
		System.out.println("Take one down and pass it around, 38 bottles of beer on the wall.");
		System.out.println("38 bottles of beer on the wall, 38 bottles of beer.");
		System.out.println("Take one down and pass it around, 37 bottles of beer on the wall.");
		System.out.println("37 bottles of beer on the wall, 37 bottles of beer.");
		System.out.println("Take one down and pass it around, 36 bottles of beer on the wall.");
		System.out.println("36 bottles of beer on the wall, 36 bottles of beer.");
		System.out.println("Take one down and pass it around, 35 bottles of beer on the wall.");
		System.out.println("35 bottles of beer on the wall, 35 bottles of beer.");
		System.out.println("Take one down and pass it around, 34 bottles of beer on the wall.");
		System.out.println("34 bottles of beer on the wall, 34 bottles of beer.");
		System.out.println("Take one down and pass it around, 33 bottles of beer on the wall.");
		System.out.println("33 bottles of beer on the wall, 33 bottles of beer.");
		System.out.println("Take one down and pass it around, 32 bottles of beer on the wall.");
		System.out.println("32 bottles of beer on the wall, 32 bottles of beer.");
		System.out.println("Take one down and pass it around, 31 bottles of beer on the wall.");
		System.out.println("31 bottles of beer on the wall, 31 bottles of beer.");
		System.out.println("Take one down and pass it around, 30 bottles of beer on the wall.");
		System.out.println("30 bottles of beer on the wall, 30 bottles of beer.");
		System.out.println("Take one down and pass it around, 29 bottles of beer on the wall.");
		System.out.println("29 bottles of beer on the wall, 29 bottles of beer.");
		System.out.println("Take one down and pass it around, 28 bottles of beer on the wall.");
		System.out.println("28 bottles of beer on the wall, 28 bottles of beer.");
		System.out.println("Take one down and pass it around, 27 bottles of beer on the wall.");
		System.out.println("27 bottles of beer on the wall, 27 bottles of beer.");
		System.out.println("Take one down and pass it around, 26 bottles of beer on the wall.");
		System.out.println("26 bottles of beer on the wall, 26 bottles of beer.");
		System.out.println("Take one down and pass it around, 25 bottles of beer on the wall.");
		System.out.println("25 bottles of beer on the wall, 25 bottles of beer.");
		System.out.println("Take one down and pass it around, 24 bottles of beer on the wall.");
		System.out.println("24 bottles of beer on the wall, 24 bottles of beer.");
		System.out.println("Take one down and pass it around, 23 bottles of beer on the wall.");
		System.out.println("23 bottles of beer on the wall, 23 bottles of beer.");
		System.out.println("Take one down and pass it around, 22 bottles of beer on the wall.");
		System.out.println("22 bottles of beer on the wall, 22 bottles of beer.");
		System.out.println("Take one down and pass it around, 21 bottles of beer on the wall.");
		System.out.println("21 bottles of beer on the wall, 21 bottles of beer.");
		System.out.println("Take one down and pass it around, 20 bottles of beer on the wall.");
		System.out.println("20 bottles of beer on the wall, 20 bottles of beer.");
		System.out.println("Take one down and pass it around, 19 bottles of beer on the wall.");
		System.out.println("19 bottles of beer on the wall, 19 bottles of beer.");
		System.out.println("Take one down and pass it around, 18 bottles of beer on the wall.");
		System.out.println("18 bottles of beer on the wall, 18 bottles of beer.");
		System.out.println("Take one down and pass it around, 17 bottles of beer on the wall.");
		System.out.println("17 bottles of beer on the wall, 17 bottles of beer.");
		System.out.println("Take one down and pass it around, 16 bottles of beer on the wall.");
		System.out.println("16 bottles of beer on the wall, 16 bottles of beer.");
		System.out.println("Take one down and pass it around, 15 bottles of beer on the wall.");
		System.out.println("15 bottles of beer on the wall, 15 bottles of beer.");
		System.out.println("Take one down and pass it around, 14 bottles of beer on the wall.");
		System.out.println("14 bottles of beer on the wall, 14 bottles of beer.");
		System.out.println("Take one down and pass it around, 13 bottles of beer on the wall.");
		System.out.println("13 bottles of beer on the wall, 13 bottles of beer.");
		System.out.println("Take one down and pass it around, 12 bottles of beer on the wall.");
		System.out.println("12 bottles of beer on the wall, 12 bottles of beer.");
		System.out.println("Take one down and pass it around, 11 bottles of beer on the wall.");
		System.out.println("11 bottles of beer on the wall, 11 bottles of beer.");
		System.out.println("Take one down and pass it around, 10 bottles of beer on the wall.");
		System.out.println("10 bottles of beer on the wall, 10 bottles of beer.");
		System.out.println("Take one down and pass it around, 9 bottles of beer on the wall.");
		System.out.println("9 bottles of beer on the wall, 9 bottles of beer.");
		System.out.println("Take one down and pass it around, 8 bottles of beer on the wall.");
		System.out.println("8 bottles of beer on the wall, 8 bottles of beer.");
		System.out.println("Take one down and pass it around, 7 bottles of beer on the wall.");
		System.out.println("7 bottles of beer on the wall, 7 bottles of beer.");
		System.out.println("Take one down and pass it around, 6 bottles of beer on the wall.");
		System.out.println("6 bottles of beer on the wall, 6 bottles of beer.");
		System.out.println("Take one down and pass it around, 5 bottles of beer on the wall.");
		System.out.println("5 bottles of beer on the wall, 5 bottles of beer.");
		System.out.println("Take one down and pass it around, 4 bottles of beer on the wall.");
		System.out.println("4 bottles of beer on the wall, 4 bottles of beer.");
		System.out.println("Take one down and pass it around, 3 bottles of beer on the wall.");
		System.out.println("3 bottles of beer on the wall, 3 bottles of beer.");
		System.out.println("Take one down and pass it around, 2 bottles of beer on the wall.");
		System.out.println("2 bottles of beer on the wall, 2 bottles of beer.");
		System.out.println("Take one down and pass it around, 1 bottle of beer on the wall.");
		System.out.println("1 bottle of beer on the wall, 1 bottle of beer.");
		System.out.println("Take 1 down and pass it around, no more bottles of beer on the wall.");
		System.out.println("No more bottles of beer on the wall, no more bottles of beer.");
		System.out.println("Go to the store and buy some more, 99 bottles of beer on the wall.");
	}
	
}
